# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-05 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
